'use strict';
const express=require('express');
const router=express.Router();
const {protect,authorize}=require('../middleware/authMiddleware');
const c=require('../controllers/homeBannerController');
router.get('/',c.getActiveBanners);
router.get('/all',protect,authorize('admin'),c.getAllBanners);
router.post('/',protect,authorize('admin'),c.createBanner);
router.put('/reorder',protect,authorize('admin'),c.reorderBanners);
router.patch('/:id/toggle',protect,authorize('admin'),c.toggleBanner);
router.put('/:id',protect,authorize('admin'),c.updateBanner);
router.delete('/:id',protect,authorize('admin'),c.deleteBanner);
module.exports=router;
