const express  = require('express');
const { body } = require('express-validator');
const rateLimit = require('express-rate-limit'); // Ensure you ran: npm install express-rate-limit
const router   = express.Router();

const {
  sendOTPHandler, verifyOTPHandler, register, login,
  requestPasswordReset, verifyPasswordResetOTP, resetPassword,
  getProfile, updateProfile,
  getAddresses, addAddress, updateAddress, deleteAddress, setDefaultAddress,
} = require('../controllers/userController');

const { protect }  = require('../middleware/authMiddleware');
const validate     = require('../middleware/validateMiddleware');

// ── Rate Limiters ─────────────────────────────────────────────
const otpLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour window
  max: 5, // Limit each IP to 5 OTP requests per hour to save SMS costs
  message: { success: false, message: 'Too many OTP requests. Please try again in an hour.' },
  standardHeaders: true,
  legacyHeaders: false,
});

const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes window
  max: 7, // Limit each IP to 7 login/verify attempts per 15 minutes
  message: { success: false, message: 'Too many login attempts. Please try again in 15 minutes.' },
  standardHeaders: true,
  legacyHeaders: false,
});

// ── Auth ──────────────────────────────────────────────────────
router.post('/send-otp',
  otpLimiter, // Applied to protect SMS wallet
  [body('phone').notEmpty().withMessage('Phone is required')],
  validate, sendOTPHandler
);

router.post('/verify-otp',
  loginLimiter,
  [
    body('phone').customSanitizer((value) => String(value || '').trim()),
    body('phone').notEmpty().withMessage('Phone is required'),
    // Accept only the four numeric digits generated by the OTP service.
    // Sanitizing here prevents mobile/browser input formatting from causing
    // a false 422 validation failure (spaces, non-breaking spaces, etc.).
    body('otp').customSanitizer((value) => String(value || '').replace(/\D/g, '').slice(0, 4)),
    body('otp').isLength({ min: 4, max: 4 }).withMessage('OTP must be 4 digits'),
  ],
  (req, res, next) => {
    console.log(`[OTP-VERIFY] request phone=${String(req.body?.phone || '').replace(/(\+91|\+?91)?(\d{2})\d{6}(\d{2})$/, '$1$2******$3')} otpLength=${String(req.body?.otp || '').length}`);
    next();
  },
  validate, verifyOTPHandler
);

router.post('/forgot-password',
  otpLimiter,
  [body('phone').notEmpty().withMessage('Phone is required')],
  validate, requestPasswordReset
);

router.post('/forgot-password/verify',
  loginLimiter,
  [body('phone').notEmpty().withMessage('Phone is required'), body('otp').isLength({ min: 4, max: 4 }).withMessage('OTP must be 4 digits')],
  validate, verifyPasswordResetOTP
);

router.post('/forgot-password/reset',
  loginLimiter,
  [body('phone').notEmpty().withMessage('Phone is required'), body('resetToken').notEmpty().withMessage('Reset session is required'), body('password').isLength({ min: 6 }).withMessage('Password must be at least 6 characters')],
  validate, resetPassword
);

router.post('/register',
  loginLimiter,
  [
    body('phone').notEmpty().withMessage('Phone is required'),
    body('password').isLength({ min: 6 }).withMessage('Password must be at least 6 characters'),
  ],
  validate, register
);

router.post('/login',
  loginLimiter,
  [
    body('phone').notEmpty().withMessage('Phone is required'),
    body('password').notEmpty().withMessage('Password is required'),
  ],
  validate, login
);

// ── Profile ───────────────────────────────────────────────────
router.get('/profile',  protect, getProfile);
router.put('/profile',  protect, updateProfile);

// ── Addresses ────────────────────────────────────────────────
router.get   ('/addresses',              protect, getAddresses);
router.post  ('/addresses',              protect,
  [
    body('house').notEmpty().withMessage('House / flat is required'),
    body('area').notEmpty().withMessage('Area is required'),
  ],
  validate, addAddress
);
router.put   ('/addresses/:id',          protect, updateAddress);
router.delete('/addresses/:id',          protect, deleteAddress);
router.patch ('/addresses/:id/default',  protect, setDefaultAddress);

module.exports = router;
