const express  = require('express');
const { body, param } = require('express-validator');
const rateLimit = require('express-rate-limit'); // Ensure you ran: npm install express-rate-limit
const router   = express.Router();

const {
  sendOTPHandler, verifyOTPHandler, register, login, logout,
  getProfile, updateProfile, requestEmailPasswordReset, verifyEmailPasswordResetOTP,
  resetPasswordByEmailOTP,
  getAddresses, addAddress, updateAddress, deleteAddress, setDefaultAddress,
} = require('../controllers/userController');

const { protect }  = require('../middleware/authMiddleware');
const validate     = require('../middleware/validateMiddleware');

// ── Rate Limiters ─────────────────────────────────────────────
const otpLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour window
  max: 5, // Limit each IP to 5 OTP requests per hour to save SMS costs
  message: { success: false, message: 'Too many OTP requests. Please try again in an hour.' },
  standardHeaders: true,
  legacyHeaders: false,
});

const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes window
  max: 7, // Limit each IP to 7 login/verify attempts per 15 minutes
  message: { success: false, message: 'Too many login attempts. Please try again in 15 minutes.' },
  standardHeaders: true,
  legacyHeaders: false,
});

// ── Auth ──────────────────────────────────────────────────────
router.post('/send-otp',
  otpLimiter, // Applied to protect SMS wallet
  [body('phone').notEmpty().withMessage('Phone is required')],
  validate, sendOTPHandler
);

router.post('/verify-otp',
  loginLimiter,
  [
    body('phone').customSanitizer((value) => String(value || '').trim()),
    body('phone').notEmpty().withMessage('Phone is required'),
    // Accept only the four numeric digits generated by the OTP service.
    // Sanitizing here prevents mobile/browser input formatting from causing
    // a false 422 validation failure (spaces, non-breaking spaces, etc.).
    body('otp').customSanitizer((value) => String(value || '').replace(/\D/g, '').slice(0, 4)),
    body('otp').isLength({ min: 4, max: 4 }).withMessage('OTP must be 4 digits'),
  ],
  (req, res, next) => {
    console.log(`[OTP-VERIFY] request phone=${String(req.body?.phone || '').replace(/(\+91|\+?91)?(\d{2})\d{6}(\d{2})$/, '$1$2******$3')} otpLength=${String(req.body?.otp || '').length}`);
    next();
  },
  validate, verifyOTPHandler
);

// Customer password recovery: email OTP. No reset link is emailed.
router.post('/forgot-password/email',
  otpLimiter,
  [body('email').isEmail().withMessage('Valid email is required')],
  validate, requestEmailPasswordReset
);

router.post('/forgot-password/email/verify',
  loginLimiter,
  [
    body('email').isEmail().withMessage('Valid email is required'),
    body('otp').customSanitizer((value) => String(value || '').replace(/\D/g, '').slice(0, 6)),
    body('otp').isLength({ min: 6, max: 6 }).withMessage('OTP must be 6 digits'),
  ],
  validate, verifyEmailPasswordResetOTP
);

router.post('/forgot-password/email/reset',
  loginLimiter,
  [
    body('resetToken').isString().isLength({ min: 40, max: 128 }).withMessage('Valid reset session is required'),
    body('password').isString().isLength({ min: 8, max: 128 }).withMessage('Password must be 8-128 characters'),
  ],
  validate, resetPasswordByEmailOTP
);

router.post('/register',
  loginLimiter,
  [
    body('phone').notEmpty().withMessage('Phone is required'),
    body('password').isLength({ min: 6 }).withMessage('Password must be at least 6 characters'),
  ],
  validate, register
);

router.post('/login',
  loginLimiter,
  [
    body('identifier').optional().isString().isLength({ min: 3, max: 254 }).withMessage('Invalid email or mobile number'),
    body('email').optional().isString().isLength({ min: 3, max: 254 }).withMessage('Invalid email'),
    body('phone').optional().isString().isLength({ min: 10, max: 16 }).withMessage('Invalid phone number'),
    body('password').isString().isLength({ min: 1, max: 128 }).withMessage('Password is required'),
  ],
  validate, login
);

router.post('/logout', protect, logout);

// ── Profile ───────────────────────────────────────────────────
router.get('/profile',  protect, getProfile);
router.put('/profile',  protect,
  [
    body('name').optional().isString().trim().isLength({ min: 1, max: 80 }).withMessage('Name must be 1-80 characters'),
    body('email').optional({ values: 'falsy' }).isEmail().withMessage('Enter a valid email address'),
    body('phone').optional().isString().isLength({ min: 10, max: 20 }).withMessage('Enter a valid mobile number'),
    body('password').optional().isString().isLength({ min: 8, max: 128 }).withMessage('Password must be 8-128 characters'),
    body('vegOnly').optional().isBoolean().withMessage('vegOnly must be boolean'),
    body('avatar').optional({ values: 'null' }).isString().isLength({ max: 2048 }).withMessage('Avatar value is too long'),
    body('adultConfirmed').optional().isBoolean().withMessage('adultConfirmed must be boolean'),
  ],
  validate, updateProfile
);

// ── Addresses ────────────────────────────────────────────────
router.get   ('/addresses',              protect, getAddresses);
router.post  ('/addresses',              protect,
  [
    body('house').notEmpty().withMessage('House / flat is required'),
    body('area').notEmpty().withMessage('Area is required'),
  ],
  validate, addAddress
);
const addressIdValidation = [param('id').isMongoId().withMessage('Invalid address ID')];
const addressFieldValidation = [
  body('tag').optional().isString().trim().isLength({ min: 1, max: 30 }),
  body('house').optional().isString().trim().isLength({ min: 1, max: 120 }),
  body('area').optional().isString().trim().isLength({ min: 1, max: 160 }),
  body('landmark').optional().isString().trim().isLength({ max: 160 }),
  body('city').optional().isString().trim().isLength({ min: 1, max: 80 }),
  body('pincode').optional().isString().matches(/^\d{6}$/).withMessage('Pincode must be 6 digits'),
  body('isDefault').optional().isBoolean().withMessage('isDefault must be boolean'),
  body().custom((value) => {
    const hasCoords = value.coordinates !== undefined || value.latitude !== undefined || value.longitude !== undefined;
    if (!hasCoords) return true;
    let longitude, latitude;
    if (Array.isArray(value.coordinates) && value.coordinates.length === 2) {
      [longitude, latitude] = value.coordinates.map(Number);
    } else if (value.coordinates !== undefined) {
      throw new Error('Coordinates must contain longitude and latitude');
    } else {
      longitude = Number(value.longitude);
      latitude = Number(value.latitude);
    }
    if (!Number.isFinite(longitude) || !Number.isFinite(latitude) || longitude < -180 || longitude > 180 || latitude < -90 || latitude > 90) {
      throw new Error('Coordinates are invalid');
    }
    return true;
  }),
];
router.put   ('/addresses/:id',          protect, addressIdValidation, addressFieldValidation, validate, updateAddress);
router.delete('/addresses/:id',          protect, addressIdValidation, validate, deleteAddress);
router.patch ('/addresses/:id/default',  protect, addressIdValidation, validate, setDefaultAddress);

module.exports = router;
