'use strict';
const mongoose=require('mongoose'); const Coupon=require('../models/Coupon'); const Redemption=require('../models/CouponRedemption'); const Order=require('../models/Order');
function admin(req,res){if(req.user?.role!=='admin'){res.status(403).json({success:false,message:'Admin credentials required.'});return false}return true}
function normalize(code){return String(code||'').trim().toUpperCase()}
async function validateCoupon(code,userId,subtotal,restaurantId){const c=await Coupon.findOne({code:normalize(code),isActive:true,startsAt:{$lte:new Date()},$or:[{expiresAt:null},{expiresAt:{$gt:new Date()}}]});if(!c)return {ok:false,message:'Coupon is invalid or expired.'};if(Number(subtotal)<Number(c.minSubtotal||0))return {ok:false,message:`Minimum subtotal for this coupon is ₹${c.minSubtotal}.`};if(c.restaurant&&String(c.restaurant)!==String(restaurantId))return {ok:false,message:'Coupon is not valid for this restaurant.'};if(c.usageLimit!=null&&c.usedCount>=c.usageLimit)return {ok:false,message:'Coupon usage limit has been reached.'};const used=await Redemption.countDocuments({coupon:c._id,user:userId});if(used>=Number(c.perUserLimit||1))return {ok:false,message:'You have already used this coupon.'};if(c.firstOrderOnly&&await Order.exists({user:userId,status:'delivered'}))return {ok:false,message:'This coupon is for first orders only.'};let discount=c.type==='percent'?Number(subtotal)*Number(c.value)/100:Number(c.value);if(c.maxDiscount!=null)discount=Math.min(discount,Number(c.maxDiscount));discount=Math.max(0,Math.min(discount,Number(subtotal)));return {ok:true,coupon:c,discount:Math.round(discount*100)/100}}
exports.validate=async(req,res)=>{if(!req.user)return res.status(401).json({success:false,message:'Authentication required.'});const out=await validateCoupon(req.body?.code,req.user._id,Number(req.body?.subtotal)||0,req.body?.restaurantId);if(!out.ok)return res.status(400).json({success:false,message:out.message});res.json({success:true,data:{code:out.coupon.code,discount:out.discount,type:out.coupon.type}})};
exports.create=async(req,res)=>{if(!admin(req,res))return;const b=req.body||{};const code=normalize(b.code);if(!/^[A-Z0-9_-]{3,40}$/.test(code))return res.status(400).json({success:false,message:'Invalid coupon code.'});const c=await Coupon.create({...b,code});res.status(201).json({success:true,data:c})};
exports.list=async(req,res)=>{if(!admin(req,res))return;res.json({success:true,data:await Coupon.find().sort({createdAt:-1}).lean()})};
exports.toggle=async(req,res)=>{if(!admin(req,res))return;const c=await Coupon.findByIdAndUpdate(req.params.id,{$set:{isActive:!!req.body.isActive}},{new:true});if(!c)return res.status(404).json({success:false,message:'Coupon not found.'});res.json({success:true,data:c})};
exports.validateCoupon=validateCoupon;
